/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "main.h"

bool_t
xdr_student(XDR *xdrs, student *objp)
{

	if (!xdr_string(xdrs, &objp->nume, ~0))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->grupa, ~0))
		return (FALSE);
	return (TRUE);
}
