/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "tema.h"

bool_t
xdr_sum_data(XDR *xdrs, sum_data *objp)
{

	if (!xdr_int(xdrs, &objp->x))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->y))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_access_token_req_struct(XDR *xdrs, access_token_req_struct *objp)
{

	if (!xdr_string(xdrs, &objp->client_id, ~0))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->auth_token, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_access_token_res_struct(XDR *xdrs, access_token_res_struct *objp)
{

	if (!xdr_string(xdrs, &objp->access_token, ~0))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->refresh_token, ~0))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->expires_in))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->error, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_validate_action_req_struct(XDR *xdrs, validate_action_req_struct *objp)
{

	if (!xdr_string(xdrs, &objp->access_token, ~0))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->opeation_type, ~0))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->resource, ~0))
		return (FALSE);
	return (TRUE);
}
