/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "tema.h"

char **
req_auth_1_svc(char **argp, struct svc_req *rqstp)
{

	static char * result;

	/*
	 * insert server code here
	 */

	return(&result);
}
