/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEMA_H_RPCGEN
#define _TEMA_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct sum_data {
	int x;
	int y;
};
typedef struct sum_data sum_data;
#ifdef __cplusplus
extern "C" bool_t xdr_sum_data(XDR *, sum_data*);
#elif __STDC__
extern  bool_t xdr_sum_data(XDR *, sum_data*);
#else /* Old Style C */
bool_t xdr_sum_data();
#endif /* Old Style C */


struct access_token_req_struct {
	char *client_id;
	char *auth_token;
	int refresh_token_needed;
};
typedef struct access_token_req_struct access_token_req_struct;
#ifdef __cplusplus
extern "C" bool_t xdr_access_token_req_struct(XDR *, access_token_req_struct*);
#elif __STDC__
extern  bool_t xdr_access_token_req_struct(XDR *, access_token_req_struct*);
#else /* Old Style C */
bool_t xdr_access_token_req_struct();
#endif /* Old Style C */


struct access_token_res_struct {
	char *access_token;
	char *refresh_token;
	int valability;
	char *error;
};
typedef struct access_token_res_struct access_token_res_struct;
#ifdef __cplusplus
extern "C" bool_t xdr_access_token_res_struct(XDR *, access_token_res_struct*);
#elif __STDC__
extern  bool_t xdr_access_token_res_struct(XDR *, access_token_res_struct*);
#else /* Old Style C */
bool_t xdr_access_token_res_struct();
#endif /* Old Style C */


struct validate_action_req_struct {
	char *access_token;
	char *opeation_type;
	char *resource;
};
typedef struct validate_action_req_struct validate_action_req_struct;
#ifdef __cplusplus
extern "C" bool_t xdr_validate_action_req_struct(XDR *, validate_action_req_struct*);
#elif __STDC__
extern  bool_t xdr_validate_action_req_struct(XDR *, validate_action_req_struct*);
#else /* Old Style C */
bool_t xdr_validate_action_req_struct();
#endif /* Old Style C */


#define AUTH_PROG ((rpc_uint)1)
#define AUTH_VERS ((rpc_uint)1)

#ifdef __cplusplus
#define req_auth ((rpc_uint)1)
extern "C" char ** req_auth_1(char **, CLIENT *);
extern "C" char ** req_auth_1_svc(char **, struct svc_req *);
#define req_access_token ((rpc_uint)2)
extern "C" struct access_token_res_struct * req_access_token_1(struct access_token_req_struct *, CLIENT *);
extern "C" struct access_token_res_struct * req_access_token_1_svc(struct access_token_req_struct *, struct svc_req *);
#define req_validate_action ((rpc_uint)3)
extern "C" char ** req_validate_action_1(struct validate_action_req_struct *, CLIENT *);
extern "C" char ** req_validate_action_1_svc(struct validate_action_req_struct *, struct svc_req *);

#elif __STDC__
#define req_auth ((rpc_uint)1)
extern  char ** req_auth_1(char **, CLIENT *);
extern  char ** req_auth_1_svc(char **, struct svc_req *);
#define req_access_token ((rpc_uint)2)
extern  struct access_token_res_struct * req_access_token_1(struct access_token_req_struct *, CLIENT *);
extern  struct access_token_res_struct * req_access_token_1_svc(struct access_token_req_struct *, struct svc_req *);
#define req_validate_action ((rpc_uint)3)
extern  char ** req_validate_action_1(struct validate_action_req_struct *, CLIENT *);
extern  char ** req_validate_action_1_svc(struct validate_action_req_struct *, struct svc_req *);

#else /* Old Style C */
#define req_auth ((rpc_uint)1)
extern  char ** req_auth_1();
extern  char ** req_auth_1_svc();
#define req_access_token ((rpc_uint)2)
extern  struct access_token_res_struct * req_access_token_1();
extern  struct access_token_res_struct * req_access_token_1_svc();
#define req_validate_action ((rpc_uint)3)
extern  char ** req_validate_action_1();
extern  char ** req_validate_action_1_svc();
#endif /* Old Style C */

#endif /* !_TEMA_H_RPCGEN */
